### ISSUE TITLE
Add option for allowInternals

### ISSUE THREAD

**Issue by Nargonath** [antonsamper/hapi-cron#33]
Right now the plugin requires that the route of the CRON job is public. However for most CRON jobs the route should not be accessible to the outsite world especially since most of them are using also `auth: false` . The problem is that if we declare the route as `isInternal: true` the plugin would not be able to call it since the inject method does not have its option `allowInternals: true` : https://github.com/antonsamper/hapi-cron/blob/3201cce4b05248cb1da3b0ff1e00d8b774c352c3/lib/index.js#L22.

**Comment by antonsamper** [comment]
I’ll look at implementing this feature over the next few days

**Comment by Nargonath** [comment]
Alright, I can also make a PR if you want. It is just a matter of adding the option to inject. You don't need to expose an option for that since it shouldn't impact existing behavior.

**Comment by antonsamper** [comment]
@Nargonath sure, go ahead, thanks 🙂

**Comment by antonsamper** [comment]
@Nargonath Just been looking into this and it looks like the existing plugin functionality will support what you need. Have you tried passing it in as option through the plugin options?

```js
request: {
  method: 'GET',
  url: '/test-url',
  allowInternals: true
}
```

**Comment by Nargonath** [comment]
Yeah you are right. This would definitely work. My bad.
