### ISSUE TITLE
onComplete not getting response

### ISSUE THREAD

**Issue by SuperTony0** [antonsamper/hapi-cron#8]
The documentation for this plugin says 
```
onComplete - Function to run after the route has been requested. The function will contain the response from the request 
```

but it doesn't appear that anything is being passed to the onComplete function.  Is this an oversight or is there some other way I am supposed to access the `res` from the request in the onComplete?

https://github.com/antonsamper/hapi-cron/blob/855eb7ed32801c97dd9546765647e2d6247b12ee/lib/index.js#L24

this job always logs undefined no matter what I respond with from my route 

```
jobs: [{
            name: 'Refresh Credentials',
            time: '0/10 * * * * * ',
            timezone: 'Europe/London',
            request: {
              method: 'GET',
              url: '/api/auth/credentials',
            },
            onComplete: (response) => {
              console.log('response', response)
            }
          }],
```

**Comment by antonsamper** [comment]
Thanks for raising this issue. @agchou has raised a pr with the fixed so ill get it merged in.

**Comment by antonsamper** [comment]
@SuperTony0 the latest version `1.0.3` fixes this issue. Can you confirm that it works on your end? Just want to make sure that it fixes your use case. Thanks

**Comment by SuperTony0** [comment]
Yup!  Thanks for getting on this, that took care of it
